# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170608_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_name',
            new_name='name',
        ),
    ]
